# Site settings
title: jwchriste.uk
email: jwchristie.jc@gmail.com
description:
url: "http://jwchristie.uk"
# baseurl: /new_jekyll
twitter_username: codinged
github_username:  jchristie55332

# Build settings
markdown: kramdown

github: "https://github.com/jchristie55332"
twitter: "https://twitter.com/codinged"
linkedin: "https://uk.linkedin.com/in/jameschristie1"
email: "mailto:jwchristie.jc@gmail.com"
