# Site settings
title: Jwchriste.uk
email: jwchristie.jc@gmail.com
description:
url: "http://jwchristie.uk"
# baseurl: /new_jekyll
twitter_username: codinged
github_username:  jchristie55332

# Build settings
markdown: kramdown
